name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Publish
      run: dotnet publish Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj -c Release -o website
    
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: webapp
        path: website/**
        if-no-files-found: warn
  
  deploy: # <--- first line here
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.8
        with:
          name: webapp
          path: webapp

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS}}

      - name: Deploy web app
        uses: azure/webapps-deploy@v2
        with:
          app-name: tailspin123smhuerta
          package: webapp

      - name: logout az cli
        run: az logout

