name: Issue Workflow
on:
  issues:
    types:
      - labeled
      - opened
jobs:
  get-issue-info:
    if: github.event.label.name == 'checked'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Read body
        run: echo 'Body ${{ github.event.issue.body }}'
