name: Issue Workflow
on:
  issues:
    types:
      - labeled
      - opened
jobs:
  get-issue-info:
    if: github.event.label.name == 'checked'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write
    env:
      FILENAME: ${{ github.event.issue.id }}
      BODY: "${{ github.event.issue.body }} "
    steps:
      - name: Read body
        run: echo 'Body ${{ github.event.issue.body }}'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create file
        run:  |
          cd Tailspin.SpaceGame.Web
          New-item -Path . -Name "${{env.FILENAME}}.md"
          $content = ${{env.BODY}}
          $content.GetType()
        shell: pwsh
