name: Issue Workflow
on:
  issues:
    types:
      - labeled
      - opened
jobs:
  get-issue-info:
    if: github.event.label.name == 'check'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        run: |
	echo 'Body ${{ github.event.issue.body }}'
